project:
  type: website
  preview: 
    port: 1111
    browser: false
website:
  navbar:
    left:
      - text: "Index"
        href: index.qmd
      - text: "Coding Notebook APIs"
        href: code-databases-api.qmd
format:
  html:
    page-layout: article
    css: style.css
execute:
  freeze: auto
author: Lukas Schmoigl
